# Generated by Django 5.1.1 on 2025-04-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='phones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('display_size', models.CharField(max_length=50)),
                ('battery_capacity', models.CharField(max_length=50)),
                ('camera_resolution', models.CharField(max_length=50)),
                ('storage_capacity', models.CharField(max_length=50)),
                ('ram', models.CharField(max_length=50)),
                ('processor', models.CharField(max_length=50)),
                ('os', models.CharField(max_length=50)),
                ('release_date', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=100000)),
            ],
            options={
                'db_table': 'phones',
            },
        ),
    ]
