# Generated by Django 5.1.1 on 2025-04-13 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='customuser',
        ),
    ]
